# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw test

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

# Needed for the unittests
services:
  - mysql

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "Jo/3EzONsNP2Om+9daZAipWySPx7LzdKAQZHd+yGFURNQMsYBwP+d4afvf8JMmap2WqEzbF+oAhmDVOsEHzR3+3QivEjmHI53Xjbfwl8FQ94p2RHGoRNQkhHX2xEYoIz+0HEaVgdgQc8v9F20UT5WTp2qbMCME0b9gp9g31bvGKkE9H8Gv7wA+cdSKOfkhi1+8aah1YUG72dFvKj24+T0c3TOleKPgA59VcukL/2U+/Lzx4fPGneHOlTBe9Iz0lKmJZ0dScIIu4cf77/bsPMNEN9sd2o7nqyKvPStmNVhZ2v2/dn7qxUPZKbfP/+SwzPxbFGqghEwwlKWyfNoxswLgrIg9SSKvDVGJuarVnzqm7sismlLbswTTPGoGou0rxcR9aAOYr7T0J95RVTQP83yGFe5pswoCyqapZYNyp29JLTkNGknqDYnZVD8uxRXTxu8ki5EnXL4RLHgDfcdPzAEuUb08nTSc8LazeozaDfNFLGJta4dTH4eEj0UFjJexCfp6fnOQ0usB3o3SigYX7ODPQzhBJqnABDbVkraH1hL2K3p79h2XeNgLQhIMEQWJq0TNewGhYZ/Jm/2b3DGVhf/RJkk8UaOqHjr5MyTuFYfRU+lCtL2VeP3tFiZ4KBCWY9+56v8tIkxGKNvqMfKE2UEIYQMDs2d2LntTuPSX+hTOs="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "wRZCmTIbtG6oy1dal6j/bKMzXhdDJ6XM8t+OCW+KKSTzzBuGdzVzmvdrdTm93l23dFatnchHT7dKP25Ol5iJaZKG144NOErLWX5EII/k9z6FCxCszT/yZQgqCoD8P5yDIAH55NVBEh9NBkpPkiWQ8HsuhLJno3mUEGA+I/KOwFmpUeBa9IHsiwRtZnQD/wA/Ogch1aTPL0/H78/i1r/l9ZtriCU5MnJ/8Ixio0VrKD5/HZG+9RcFlH79PxtDIG9luDwDg7A9DZWuYltkM/BlBAtogIWC8jY0gWLDD4+0s9bIEgdD2hP5xIVfaolGkpjUrggQBIO1GbOtwsjz8fkyVZu9Vy/va2mSqUuSGm3KFyeXFrVV2b025TIAUbxf8/XiLJguZwYJV5PAYcUljQz8cr3WN6bRHMQRmri5nsupKZGjfeA6/ncKloD+Jklw+n1gjlO1LKa+4SztAeReJaTzuY3RB854783VtUnVTpefqI6L4WjBYVHWA6nWWeUeMZgD6yfNmCOska/JjZ2v8N+XwFqOJ1NjMxJlMEkoWXv6Fiystyg/67udp9QWjLYaNTWEBvOTIAsXTe+bct8O8bIfqWUTCPphfwKX1idTxiFu29pjiBQxfNXcpT61oBHJT2n7paHE48wMIlw03aLAwKgQ6wXhBDjSz8dlKECqQIHrCTM="
  # Ex. travis encrypt GH_USER_EMAIL=for_github@domain.com --add
  - secure: "IVjeiSbTlfluVXBeo/WChu1hKWKE9mhlDbN4AR/nwOSu2+ITLD2Bqmqbd3Zylf9h5Oz5Lp191lPOk1e3wGGjP6c4FbMaxSI9rBn1OoZz5SMHdbMxaHxzKfTUKjNkoyNia4aDzt7o03d4exNXppL1cY5DQDG13lsc3jV3hV8acHYdxPzTEyVHtRboAtX520COufCwVHNqUsGb69jwbnzzfBIdbgG9mD13v3uM2BckYPMH8/S7F/7OAtvzOm/Lcfn57xnBAf3SWptNIfT1IllZ0hNk1b6Y4vwiG2QtM4fcQXBxvOHnoVHtacaRo4/PUPv55xinJWlFcUlM5pdrIFn6UK2qQdxIXlcisymvcdauX+bREbXDkzxRq6uHPJi+2CGMn1qFyOObaoWsJul8zCrZp1TKLS7wIkDkK284/4w4vk5mCuhsfUPnv8PfiBhMR6zFD2kkhrHhdCvyJzNT0rKYgQaqtl4Sd7TdvliXiObqg0qinqaWaTzUEEgbHt6SnGrXEvgINZw91+aXKJXhPOnDrFJp1rLeABGMiYQJ+hI4S7VR+bPMyD5TEjLfLtuCxYkjJJvwpJUx5yymvbcHFWTL6BVz2d6MKaOFP50L9B1VH5HYEWdy3ojMwhIy90Uy6MkLBU0CM980ZwrADIdTVhTI58lzfzZIoOw1dcJSNLf327E="
  # Ex. travis encrypt GH_USER=your_github_account --add
  - secure: "WVzIjK1WwNPnVqd4T7JJyv/MHb+3k3eOXE/8u97GuOcNKKPSXdmP3hrr9dOmFqfTWL3U976/iqNSH255Ota7XJj5ifuSRTOaQUy9ZX9m/vLBWfaCq2oxAi/HHHO//EAXZDCi6j2aTbHkhihEBWf7bT3ExRxR0R6o4f9/io06/ifsEjfzCEADNNhXt6nbqfrlxjwBDELFHEp8GdspWbkvqr+qbWjPgPjXfHZenozXzn7+UdD9VSo3JMXbPvL/+C0/kuy4qlcN6gaiC3jaKTsrvqw4eZCrrBkGF7IVuCLQh9qH/aMIJL2I6+GLImJtz1rDjSTOfwlMaHQfYppRp4+/zfwMZh5MOroOCW4NUS88d2LyfuCZ0ABblD3OaNfED89EvnR2llND9adJcC6Pscr2JWO7VDT1K6XokvGMJVHojCm9K80swu5iIvaCDOgqPjJv4iR5fxYf2miILWBN7S+AjSh9E7suiaXRVc9gE1332v621ioXXhAo5sHhUQDq65EJppCFrtZ0KnWx1REloyKgEZJr9DOGsJdcNc/STeESywzN+3i38vc2Dv9YHZwqEHDq8sws8UDAqyK8+7zMVTaIoMq30hmpCD+QxpH8r5DYnYeqDNoVdsRsKtRPYHEmHtdOI3t43vgAoWgHAj0b6dLZE+E8msN5pG103qvIMBuxAjI="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "L0/viOpaMlIS3sz67dS9kt+AOOcEDx9B7nwUurBhrRvgvExKK1DNGGVtXbkFDWVBOjUMq2dff8AW65PSfimjStYGU7fvBQST1BbjAtIFvld934ME/j1KdhSkSNBHc7/qrx7bFAyXFsVz45zHePAx1yW+zSAi0mEEUxQYOPQb652H8nSHp83EBk8GLRtXoekpmTGZGvA5w2BmrxZpOHaxMQbPXWITnF8f+Y8JcsCuWtPqGDWLbrXFcOXNkNQi72/qKKbf7n6gI7eu2wC6cvzzFokPn5/3KXWsM0NxjVp156v9N0x35eDJAHKYaj3Y6t+MDXeh+vDoamxcMmaHodLpi7ioBw56+b7M1SVvKr7B35ntjtd59HJJ+rIKYKuBeYx3IGq4dQaWWi24CvJMq70Mld+sPuY+cS+fyamwkPAYU/4ZQwlhA8V/9FUY3LZbtJ7SeM8AIE2HAfCY0KDE0epYg/GtUeAtuhEnkLCFW97SaiX2av6IutCswdTZxQQWbAt4Hg/1saADDWCPanFk/IodnTCBXtCO3+REcSnujoT8PSP8gt4xzR/J8cu/ikHHwhH6fJuuAH743HErImQkQBOXOc5zuBjYqo7ogK1l2sdwybjmlOM6tLihFJnQzDV8IMT8XgLzavJPeOS1rMZCz26GU2+GmF3D7hjYkoMCY2zGzCY="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "hbyXv6qSgCpAtzckW7ZBVTbwHIFspG7WEUNxRXDg1f63fiiB01OQRDl8o+FW0UnUFq07hsThiHHqkifT1MqR54z8p0xeqU4UreI7yTjUf0+H/MKx1rhFJHx4fdvutZj0lPtdepBJ2vwI9yyqoSvZNAGX6f6aZPoK+Wnb1dA7KIFTBzv8HJ/3KCmEDt/KMEu8gUkc8L33yJ8gPXRwxty3WyVwUbDMtSlNStLwkhJkCEuKQEy8Ko0ajSmiAtS3/VSwH/wpH8VKzXXvPFRcYHXOgskqDQo7PLOATdwPHXdKR9KNceHTBoT26/2FJvNxh36Zcnbu+V0MuCgFvW9EIo9uJQr6s1eov5mqn0+SJMGBQ6NYGTjwS6hzxm3b+ZMDBy5nGOUGkaPtteXBV6+mAjTuirdKcwJIZmgodLOw9HbXWCvSL9W5oc4GVW9kEQ0gXjP7q3iuQkZHLoB4Un51L9K37p3E5t1+ZCL6INCCHWwmFVF7ovYaWRUzZkky6Y3n40aPKb/rO6gX49D7QJ2psUmdyN0BDezlOYSGP1Px1lrLqGYP9vKVqGHOD+/IRLVBmkSwCMeO5VhUL9lUbpKScaaEpG+HaBlPfOsS5fE4h0QSx+rRxIYUicPXYWZ+sG8++CQWoqPwcRLVMry3q+JsOdqVDpA4TLL19s8m3o3BKaGsmp4="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "elHuLBzYG/5vYPjO7fWUiWLOfWtdWKLRMEDwgjqa61vjpYGUb5AAg/BcG5BUBmeRGwwQLdPnAlkwUXT1TUsGrYi/OIJqrGJkudZJV4cclEhyQxCs0E/vNaf1OVv1znvL1d14oPQhxaw8ib3k6cO0ak556CdCQiDAwajxMcmTaJlVsLME4rUw9j4XOybjxQZrXsg24F+HkHdckAKCUDmCwHYKtFGRj3bkz8L2XbQjlIPOttdsaMLN/vUHtCEQH4wmeA8mbgJ0IJiGll0mQTMaJiWVE2KpjBNjkY0cuSxO4dd304KikESgKixjSZnxcqpucntYcuLkY1ZrpmV3m+Zpu9X5i33hjyyuIY4Ug9vIQ3pGMDsu/X6Wgc09/TSM2Wqb+TYuTuIND5LOzkgivfx083J5JimJf9hQku1Nk0Tej0tm1QIa8BZKbi9IhCwiXYru+iu9s8GcRr1CskBzpdLpPkur/U1+tKG78nvgC5PNz9782UaNtLUtwIIy0ryFxWHp6wCvEWQjSYUNv3ndNMGwLGIztbsHCFPIdoU05mge7Xs7M8j4zJuwBk36Bl6isXl1lophSznTnePq8z/Igxk3qhjFuIWguAIvbUMl+ye9B59nqR+mWXMO+p9dNmmV6JqxqdnSpamzgX2lXh07Ebsbg5sC6mzpORJUw12SjPaEhwI="
